### ISSUE TITLE
Add way to reduce the size of the pictures

### ISSUE THREAD

**Issue by leletec** [leletec/NameMemo#3]
Add way to reduce the size of the pictures taken and maybe also from the ones on the device.
At the moment they need kind of long to load and take "a lot of" space.

**Comment by okitec** [comment]
Measure the times and try to find the real cause. Programmers almost never guess correctly where the bottleneck is. After all, the pictures  you use are used by other apps and they are not slow.

You should make sure to use only JPEG, it is the smallest for the realistic pictures you'll use. Consider re-encoding them with a lossier JPEG compression setting. Whether that is possible directly on the phone  I do not know.

**Comment by leletec** [comment]
Not necessary. Won't do that for now.

**Comment by leletec** [comment]
It seems that 2c4e5d25d3078479b9553049c036ea69037d423c made the loading quicker.
