### ISSUE TITLE
Fully implement statecontroller

### ISSUE THREAD

**Issue by leletec** [leletec/NameMemo#7]
At the moment, not all the states (especially those in other activities) are handled.
Have to find out to what extend this is necessary first.
Maybe think about SharedPreferences.

**Comment by okitec** [comment]
> At the moment, not all the states (especially those in other activities) are handled.

Find the derpage. :wink: 

Make sure you don't have more states than necessary. Also, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

**Comment by leletec** [comment]
What do you mean? :wink:
The only real purpose of the states is to reconstruct the activity when the user rotates the screen.
You could also just forbid screen-rotation.

**Comment by okitec** [comment]
You are one trollface, modifying the incorrect quote.

Just forbid rotation; your pictures are vertical.

**Comment by leletec** [comment]
Well that is a solution.
But you _could_ have pictures in landscape mode.
I will see.

**Comment by okitec** [comment]
Again, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

Implement it only when the need arises.

**Comment by leletec** [comment]
I am going to force the secondary activities (bluetooth, nfc) into portrait mode.

**Comment by leletec** [comment]
Fully removed it in 3d4fe439a2d5fd991e44b330932fe0a0592b4e00.
